import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const robotoMono = localFont({
  src: [
    {
      path: "./fonts/RobotoMono-Regular.ttf",
      weight: '400',
      style: 'normal'
    },
    {
      path: "./fonts/RobotoMono-Bold.ttf",
      weight: '900',
      style: 'normal'
    },
    {
      path: "./fonts/RobotoMono-Light.ttf",
      weight: '100',
      style: 'normal'
    },
    {
      path: "./fonts/RobotoMono-SemiBold.ttf",
      weight: '700',
      style: 'normal'
    },
    {
      path: "./fonts/RobotoMono-Medium.ttf",
      weight: '300',
      style: 'normal'
    }
  ],
  variable: "--font-roboto-mono",
  weight: "100 900",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
